import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'hi' | 'te' | 'ta' | 'ml' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isBilingual: boolean;
  toggleBilingual: () => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header & Nav
    emergencyBar: "🚨 EMERGENCY MEDICINE & AMBULANCE DIAL: 108 | TOLL-FREE: 1800-309-8800",
    navHome: "Home",
    navMedicines: "Medicines",
    navConsult: "Consult Doctor",
    navSubscription: "Health Plans",
    navDelivery: "Delivery Partners",
    navOrders: "My Orders",
    navSearch: "Image Search",
    navFamily: "Family Accounts",
    logout: "Log Out",
    cart: "Cart",
    
    // Auth / Login
    loginTitle: "Welcome to RuralCare",
    loginSubtitle: "Telemedicine & Medicine Delivery for Rural India",
    phoneLabel: "Phone Number",
    nameLabel: "Your Name",
    loginBtn: "Login with OTP / Verify",
    phonePlaceholder: "Enter 10-digit phone number",
    namePlaceholder: "Enter your full name",
    requiredFields: "Please enter your name and phone number.",
    
    // Home Page
    welcome: "Namaste, Welcome to RuralCare",
    homeSubtitle: "Bringing quality doctors and medicines directly to your village.",
    callDoctorNow: "Consult a Doctor Now",
    orderMedsNow: "Order Medicines",
    imageSearchNow: "Search Medicine by Photo",
    manageFamilyNow: "Manage Family Members",
    emergencyContact: "Emergency Contacts",
    ambulance108: "Emergency Ambulance: 108",
    ruralCareTollFree: "RuralCare Helpdesk: 1800-309-8800",
    healthTipTitle: "Today's Health Tip",
    healthTipContent: "Drink water stored in copper vessels or clean boiled water to prevent stomach infections during summer.",
    
    // Medicines Page
    medicineSearchPlaceholder: "Search medicines (e.g. Paracetamol, Crocin)...",
    allCategories: "All Categories",
    feverPain: "Fever & Pain Relief",
    coldAllergy: "Cold & Allergy",
    stomachGas: "Stomach & Gas",
    vitaminsNutrition: "Vitamins & Nutrition",
    firstAid: "First Aid & Nutrition",
    bloodPressure: "Blood Pressure",
    diabetesCare: "Diabetes Care",
    genericName: "Generic Name",
    dosage: "Dosage",
    price: "Price",
    rs: "₹",
    addToCart: "Add to Cart",
    added: "Added",
    outOfStock: "Out of Stock",
    
    // Cart & Checkout
    cartTitle: "Your Cart",
    emptyCart: "Your cart is empty. Order medicines to stay healthy!",
    itemTotal: "Item Total",
    deliveryCharges: "Delivery Charges",
    free: "FREE",
    totalPayable: "Total Amount to Pay",
    proceedCheckout: "Proceed to Checkout",
    checkoutTitle: "Enter Delivery Address & Select Payment",
    fullName: "Full Name",
    village: "Village / Town",
    panchayat: "Gram Panchayat",
    district: "District",
    state: "State",
    pincode: "Pincode (6 digits)",
    selectPayment: "Choose Payment Method",
    upiPay: "UPI (Google Pay / PhonePe / Paytm)",
    cardPay: "Debit / Credit Card",
    walletPay: "Mobile Wallet",
    codPay: "Cash on Delivery (COD)",
    placeOrder: "Confirm and Place Order",
    paymentModalTitle: "Simulated Payment Gateway",
    paymentModalBody: "Scan this QR code with any UPI app on your phone, or click approve to simulate payment completion.",
    scanQrCode: "Scan QR Code for Payment",
    simulatedSuccess: "Simulate Success",
    simulatedFail: "Simulate Fail",
    orderSuccessTitle: "Order Placed Successfully!",
    orderSuccessDesc: "Your medicines will reach your village shortly. Track your status in 'My Orders'.",
    close: "Close",
    
    // Orders Page
    orderHistory: "Order History",
    noOrders: "You have not placed any orders yet.",
    orderId: "Order ID",
    status: "Status",
    payment: "Payment",
    items: "Items",
    address: "Address",
    downloadInvoice: "Download Invoice",
    orderedState: "Ordered / Booked",
    dispatchedState: "Dispatched from Center",
    outForDeliveryState: "Out for Delivery (Near Village)",
    deliveredState: "Delivered",
    
    // Consult Doctor Page
    consultTitle: "Consult Online Doctors",
    consultSubtitle: "Video, audio, or chat consultations with expert doctors from city hospitals.",
    availableDoctors: "Available Doctors Today",
    languagesSpoken: "Spoken Languages",
    consultationFee: "Consultation Fee",
    bookNow: "Book Consultation",
    consultationHistory: "Your Consultations",
    noConsultations: "No past doctor consultations found.",
    startVideoCall: "Join Video Call",
    viewPrescription: "Download Prescription",
    connecting: "Connecting to Doctor... Please enable camera and microphone.",
    hangUp: "End Consultation",
    patientName: "Patient Name",
    selectPatient: "Select Patient",
    describeSymptom: "Describe your symptoms (e.g. Fever for 2 days)",
    symptomPlaceholder: "Write symptoms here...",
    payAndStartCall: "Pay Fee & Start Call",
    
    // Subscription Page
    subTitle: "RuralCare Family Health Plans",
    subSubtitle: "Protect your family with affordable health plans starting from ₹49/month.",
    freeDelivery: "Unlimited Free Medicine Delivery",
    freeConsults: "Free Doctor Consultations",
    villageDiscount: "Additional 10% discount on medicine orders",
    subscribeBtn: "Subscribe Now",
    currentPlan: "Current Plan",
    active: "Active",
    upgrade: "Upgrade Plan",
    planBasic: "Village Shield (Basic)",
    planFamily: "Family Care (Standard)",
    planVillage: "Village Community (Premium)",
    planNone: "Free Tier (Pay-per-use)",
    
    // Delivery Partner Page
    delTitle: "Become a RuralCare Delivery Partner",
    delSubtitle: "Deliver health to your village, earn stable income, and enjoy flexible hours.",
    requirements: "Requirements",
    benefits: "Benefits & Earnings",
    reqAge: "Age: Must be 18 years or older",
    reqVehicle: "Vehicle: Own a bicycle, motorcycle, or scooter",
    reqLicense: "License: Valid Driving License (for motorcycles)",
    reqPhone: "Smartphone: Android phone with active internet connection",
    reqArea: "Local Knowledge: Good knowledge of surrounding villages & routes",
    benHours: "Flexible Hours: Work whenever you want",
    benPayouts: "Weekly Payouts: Get money transferred directly to your bank account",
    benIncentives: "Delivery Incentives: Extra earnings for night or monsoon deliveries",
    benSupport: "Insurance Cover: Accidental cover and medical support",
    registerFormTitle: "Registration Form",
    regName: "Full Name",
    regPhone: "Phone Number",
    regVehicleType: "Vehicle Type",
    regVillage: "Working Village/Block",
    regLicenseNo: "Driving License Number",
    regSubmit: "Submit Partner Application",
    regSuccess: "Thank you! Our block coordinator will contact you in 24 hours.",
    
    // Image Search Page
    searchTitle: "Search Medicines by Photo",
    searchSubtitle: "Upload a picture of your medicine pack or prescription, and our system will identify it.",
    capturePhoto: "Capture Photo",
    uploadPhoto: "Upload Photo",
    takePhoto: "Take a Photo",
    retakePhoto: "Retake Photo",
    selectFromGallery: "Select from Gallery",
    validationSize: "File size should be less than 5MB.",
    validationType: "Only JPG, JPEG, and PNG images are allowed.",
    scanning: "Scanning image... Analyzing handwriting & medicine name...",
    matchingMeds: "We found the following matching medicines in stock:",
    noMatch: "No matching medicines found. Please contact support or consult a doctor.",
    translateTitle: "Need translation? (अनुवाद चाहिए?)",
    translateBody: "If your prescription is in English, you can open the 'Google Translate' app on your phone, point the camera at the paper, and view the entire prescription translated instantly into your language.",
    translateStep1: "1. Download Google Translate app from Play Store.",
    translateStep2: "2. Open the app and select English to Hindi (or Telugu/Tamil/etc.).",
    translateStep3: "3. Tap the 'Camera' icon and hold it over your prescription paper.",
    
    // Family Accounts Page
    familyTitle: "My Family Account",
    familySubtitle: "Manage health profiles for your children, spouse, and parents under a single account.",
    addMember: "Add Family Member",
    relationship: "Relationship",
    ageYears: "Age (in years)",
    gender: "Gender",
    medicalHistory: "Past Medical History (Allergies, chronic illness)",
    relationSelf: "Self",
    relationSpouse: "Spouse",
    relationChild: "Child",
    relationParent: "Parent",
    relationSibling: "Sibling",
    relationOther: "Other",
    noFamily: "No family members added yet.",
    removeMember: "Remove Member"
  },
  hi: {
    emergencyBar: "🚨 आपातकालीन दवा और एम्बुलेंस फोन: 108 | टोल-फ्री: 1800-309-8800",
    navHome: "मुख्य पृष्ठ / Home",
    navMedicines: "दवाइयाँ / Medicines",
    navConsult: "डॉक्टर सलाह / Consult",
    navSubscription: "स्वास्थ्य योजना / Plans",
    navDelivery: "डिलीवरी पार्टनर / Delivery",
    navOrders: "मेरे आर्डर / Orders",
    navSearch: "फ़ोटो से खोजें / Search",
    navFamily: "परिवार खाते / Family",
    logout: "लॉग आउट / Logout",
    cart: "दवाओं का थैला / Cart",
    loginTitle: "रूरलकेयर में आपका स्वागत है",
    loginSubtitle: "ग्रामीण भारत के लिए ऑनलाइन डॉक्टर और दवा डिलीवरी सेवा",
    phoneLabel: "फ़ोन नंबर / Phone",
    nameLabel: "आपका नाम / Name",
    loginBtn: "ओटीपी सत्यापित करें / Verify OTP",
    phonePlaceholder: "10 अंकों का मोबाइल नंबर डालें",
    namePlaceholder: "अपना पूरा नाम डालें",
    requiredFields: "कृपया अपना नाम और फ़ोन नंबर दर्ज करें।",
    welcome: "नमस्ते, रूरलकेयर में आपका स्वागत है",
    homeSubtitle: "अच्छे डॉक्टरों और दवाइयों को सीधे आपके गांव तक पहुंचाना।",
    callDoctorNow: "अभी डॉक्टर से सलाह लें / Consult Doctor",
    orderMedsNow: "दवाइयां मंगवाएं / Order Medicines",
    imageSearchNow: "फ़ोटो खींचकर दवा खोजें / Image Search",
    manageFamilyNow: "परिवार के सदस्यों को जोड़ें / Family Accounts",
    emergencyContact: "आपातकालीन संपर्क / Emergency",
    ambulance108: "आपातकालीन एम्बुलेंस: 108",
    ruralCareTollFree: "रूरलकेयर सहायता: 1800-309-8800",
    healthTipTitle: "आज का स्वास्थ्य सुझाव",
    healthTipContent: "गर्मी के मौसम में पेट के संक्रमण से बचने के लिए तांबे के बर्तन में रखा पानी या साफ उबला हुआ पानी पिएं।",
    medicineSearchPlaceholder: "दवा खोजें (जैसे: पैरासिटामोल, क्रोसिन)...",
    allCategories: "सभी श्रेणियां / All Categories",
    feverPain: "बुखार और दर्द की दवा / Fever & Pain",
    coldAllergy: "सर्दी, जुकाम और एलर्जी / Cold & Allergy",
    stomachGas: "पेट की गैस और जलन / Stomach & Gas",
    vitaminsNutrition: "विटामिन और ताकत की दवा / Vitamins",
    firstAid: "प्राथमिक उपचार / First Aid",
    bloodPressure: "रक्तचाप / Blood Pressure",
    diabetesCare: "शुगर / Diabetes Care",
    genericName: "जेनेरिक नाम",
    dosage: "खुराक / Dosage",
    price: "कीमत / Price",
    rs: "₹",
    addToCart: "थैले में डालें / Add to Cart",
    added: "थैले में डाला गया / Added",
    outOfStock: "स्टॉक में नहीं है / Out of Stock",
    cartTitle: "आपका थैला / Cart",
    emptyCart: "आपका थैला खाली है। स्वस्थ रहने के लिए दवाइयाँ मंगवाएँ!",
    itemTotal: "दवाओं की कीमत",
    deliveryCharges: "डिलीवरी शुल्क",
    free: "मुफ़्त / FREE",
    totalPayable: "कुल भुगतान राशि",
    proceedCheckout: "ऑर्डर करने के लिए आगे बढ़ें",
    checkoutTitle: "डिलीवरी का पता और भुगतान विकल्प",
    fullName: "पूरा नाम",
    village: "गाँव या कस्बा",
    panchayat: "ग्राम पंचायत",
    district: "जिला",
    state: "राज्य",
    pincode: "पिनकोड (6 अंक)",
    selectPayment: "भुगतान का तरीका चुनें",
    upiPay: "यूपीआई (गूगल पे / फोनपे / पेटीएम)",
    cardPay: "एटीएम कार्ड / क्रेडिट कार्ड",
    walletPay: "मोबाइल वॉलेट",
    codPay: "डिलीवरी पर नकद (COD)",
    placeOrder: "ऑर्डर की पुष्टि करें",
    paymentModalTitle: "भुगतान सिम्युलेटर",
    paymentModalBody: "अपने फोन के किसी भी यूपीआई ऐप से इस क्यूआर कोड को स्कैन करें, या भुगतान पूरा करने के लिए 'मंजूर करें' बटन दबाएं।",
    scanQrCode: "भुगतान के लिए क्यूआर कोड स्कैन करें",
    simulatedSuccess: "भुगतान सफल करें / Success",
    simulatedFail: "भुगतान विफल करें / Fail",
    orderSuccessTitle: "ऑर्डर सफलतापूर्वक दर्ज हो गया है!",
    orderSuccessDesc: "आपकी दवाइयां जल्द ही आपके गांव पहुंच जाएंगी। स्टेटस जांचने के लिए 'मेरे आर्डर' देखें।",
    close: "बंद करें / Close",
    orderHistory: "आपके पुराने ऑर्डर",
    noOrders: "आपने अभी तक कोई ऑर्डर नहीं दिया है।",
    orderId: "ऑर्डर आईडी",
    status: "स्थिति / Status",
    payment: "भुगतान / Payment",
    items: "सामान / Items",
    address: "पता / Address",
    downloadInvoice: "रसीद डाउनलोड करें",
    orderedState: "ऑर्डर हो गया है",
    dispatchedState: "सेंटर से भेज दिया गया है",
    outForDeliveryState: "डिलीवरी के लिए निकल गया है",
    deliveredState: "पहुंच गया है",
    consultTitle: "ऑनलाइन डॉक्टरों से परामर्श",
    consultSubtitle: "शहर के बड़े अस्पतालों के अनुभवी डॉक्टरों से घर बैठे वीडियो या ऑडियो पर बात करें।",
    availableDoctors: "आज उपलब्ध डॉक्टर",
    languagesSpoken: "बोली जाने वाली भाषाएं",
    consultationFee: "डॉक्टर की फीस",
    bookNow: "परामर्श शुरू करें / Book",
    consultationHistory: "आपके परामर्श का इतिहास",
    noConsultations: "कोई पुराना परामर्श रिकॉर्ड नहीं मिला।",
    startVideoCall: "वीडियो कॉल में शामिल हों",
    viewPrescription: "पर्चा (प्रिस्क्रिप्शन) डाउनलोड करें",
    connecting: "डॉक्टर से संपर्क जोड़ा जा रहा है... कृपया कैमरा और माइक चालू करें।",
    hangUp: "परामर्श समाप्त करें / End Call",
    patientName: "मरीज का नाम",
    selectPatient: "मरीज चुनें",
    describeSymptom: "अपनी बीमारी या लक्षण बताएं (जैसे: 2 दिन से बुखार है)",
    symptomPlaceholder: "अपनी परेशानी यहाँ लिखें...",
    payAndStartCall: "फीस भरें और कॉल शुरू करें",
    subTitle: "रूरलकेयर ग्राम स्वास्थ्य योजनाएं",
    subSubtitle: "₹49/महीने से शुरू होने वाली योजनाओं के साथ अपने परिवार की सुरक्षा करें।",
    freeDelivery: "असीमित मुफ्त दवा डिलीवरी",
    freeConsults: "मुफ्त डॉक्टर परामर्श",
    villageDiscount: "दवाओं के ऑर्डर पर अतिरिक्त 10% छूट",
    subscribeBtn: "योजना खरीदें / Subscribe",
    currentPlan: "आपकी सक्रिय योजना",
    active: "सक्रिय / Active",
    upgrade: "योजना बदलें / Upgrade",
    planBasic: "ग्राम सुरक्षा (बेसिक)",
    planFamily: "परिवार कल्याण (मानक)",
    planVillage: "ग्राम समुदाय (प्रीमियम)",
    planNone: "फ्री सेवा (इस्तेमाल पर भुगतान)",
    delTitle: "रूरलकेयर डिलीवरी पार्टनर बनें",
    delSubtitle: "अपने गाँव में दवाइयाँ पहुँचाएँ, हर हफ्ते कमाई करें, और समय अपनी मर्जी का चुनें।",
    requirements: "आवश्यकताएं (Requirements)",
    benefits: "फायदे और कमाई (Benefits)",
    reqAge: "उम्र: 18 वर्ष या उससे अधिक होनी चाहिए",
    reqVehicle: "वाहन: साइकिल, मोटरसाइकिल या स्कूटर होना चाहिए",
    reqLicense: "लाइसेंस: मोटरसाइकिल के लिए वैध ड्राइविंग लाइसेंस",
    reqPhone: "स्मार्टफोन: इंटरनेट के साथ एंड्रॉइड फोन",
    reqArea: "क्षेत्र की जानकारी: आसपास के गांवों और रास्तों की अच्छी जानकारी",
    benHours: "सुविधानुसार काम: जब चाहें काम करें",
    benPayouts: "साप्ताहिक भुगतान: सीधे बैंक खाते में पैसे ट्रांसफर",
    benIncentives: "अतिरिक्त प्रोत्साहन: रात या बारिश में डिलीवरी के लिए अतिरिक्त पैसे",
    benSupport: "दुर्घटना बीमा सुरक्षा और चिकित्सीय सहायता",
    registerFormTitle: "आवेदन फॉर्म (Registration Form)",
    regName: "पूरा नाम",
    regPhone: "फ़ोन नंबर",
    regVehicleType: "वाहन का प्रकार",
    regVillage: "कार्य करने का गाँव / ब्लॉक",
    regLicenseNo: "ड्राइविंग लाइसेंस नंबर",
    regSubmit: "आवेदन जमा करें",
    regSuccess: "धन्यवाद! हमारे ब्लॉक समन्वयक 24 घंटे में आपसे संपर्क करेंगे।",
    searchTitle: "दवा की फोटो खींचकर खोजें",
    searchSubtitle: "दवा के रैपर या डॉक्टर के पर्चे की फोटो अपलोड करें, हमारी प्रणाली दवा की पहचान कर लेगी।",
    capturePhoto: "कैमरा से फोटो लें",
    uploadPhoto: "गैलरी से अपलोड करें",
    takePhoto: "फोटो खींचे",
    retakePhoto: "दोबारा फोटो लें",
    selectFromGallery: "गैलरी से चुनें",
    validationSize: "फोटो का साइज 5MB से कम होना चाहिए।",
    validationType: "केवल JPG, JPEG और PNG फोटो ही मान्य हैं।",
    scanning: "फोटो स्कैन की जा रही है... दवा के नाम की जांच हो रही है...",
    matchingMeds: "हमें स्टॉक में निम्नलिखित मिलती-जुलती दवाइयां मिली हैं:",
    noMatch: "कोई मिलती-जुलती दवा नहीं मिली। कृपया सहायता केंद्र से संपर्क करें या डॉक्टर से सलाह लें।",
    translateTitle: "अंग्रेजी पर्चे का हिंदी अनुवाद कैसे करें?",
    translateBody: "यदि डॉक्टर का पर्चा अंग्रेजी में है, तो अपने फोन में 'Google Translate' ऐप खोलें, कैमरे को पर्चे पर रखें और तुरंत अपनी भाषा में अनुवाद देखें।",
    translateStep1: "1. गूगल प्ले स्टोर से Google Translate ऐप डाउनलोड करें।",
    translateStep2: "2. ऐप खोलें और भाषा में English से Hindi चुनें।",
    translateStep3: "3. 'Camera' के चिन्ह पर दबाएं और इसे पर्चे के ऊपर रखें।",
    familyTitle: "मेरा परिवार खाता / Family Account",
    familySubtitle: "एक ही खाते के अंतर्गत अपने बच्चों, जीवनसाथी और माता-पिता के स्वास्थ्य प्रोफाइल का प्रबंधन करें।",
    addMember: "परिवार के सदस्य को जोड़ें",
    relationship: "रिश्ता / Relationship",
    ageYears: "उम्र (वर्षों में)",
    gender: "लिंग / Gender",
    medicalHistory: "पुरानी बीमारी (एलर्जी, अस्थमा, शुगर आदि)",
    relationSelf: "स्वयं",
    relationSpouse: "पति / पत्नी",
    relationChild: "बच्चा / बच्ची",
    relationParent: "माता / पिता",
    relationSibling: "भाई / बहन",
    relationOther: "अन्य",
    noFamily: "अभी तक परिवार का कोई सदस्य नहीं जोड़ा गया है।",
    removeMember: "सदस्य हटाएं"
  },
  te: {
    emergencyBar: "🚨 అత్యవసర వైద్య సేవలు & అంబులెన్స్: 108 | టోల్-ఫ్రీ: 1800-309-8800",
    navHome: "హోమ్ / Home",
    navMedicines: "మందులు / Medicines",
    navConsult: "వైద్యుని సంప్రదింపులు",
    navSubscription: "ఆరోగ్య ప్లాన్లు / Plans",
    navDelivery: "డెలివరీ పార్ట్నర్",
    navOrders: "నా ఆర్డర్లు / Orders",
    navSearch: "ఫొటోతో వెతకండి",
    navFamily: "కుటుంబ సభ్యులు",
    logout: "లాగ్ అవుట్ / Logout",
    cart: "మందుల బ్యాగ్ / Cart",
    loginTitle: "రూరల్ కేర్ కి స్వాగతం",
    loginSubtitle: "గ్రామీణ ప్రాంతాల కొరకు ఆన్లైన్ డాక్టర్ మరియు మందుల డెలివరీ సేవ",
    phoneLabel: "ఫోన్ నెంబర్",
    nameLabel: "మీ పేరు",
    loginBtn: "ఓటీపీ ధృవీకరణ",
    phonePlaceholder: "10 అంకెల మొబైల్ నెంబర్ నమోదు చేయండి",
    namePlaceholder: "మీ పూర్తి పేరు నమోదు చేయండి",
    requiredFields: "దయచేసి మీ పేరు మరియు ఫోన్ నంబర్‌ను నమోదు చేయండి.",
    welcome: "నమస్కారం, రూరల్ కేర్ కి స్వాగతం",
    homeSubtitle: "నాణ్యమైన వైద్య సేవలు మరియు మందులను నేరుగా మీ గ్రామానికి అందిస్తున్నాము.",
    callDoctorNow: "డాక్టర్ ని సంప్రదించండి",
    orderMedsNow: "మందులు ఆర్డర్ చేయండి",
    imageSearchNow: "ఫొటోతో మందును వెతకండి",
    manageFamilyNow: "కుటుంబ సభ్యులను చేర్చండి",
    emergencyContact: "అత్యవసర నెంబర్లు",
    ambulance108: "అంబులెన్స్ సేవ: 108",
    ruralCareTollFree: "రూరల్ కేర్ సహాయ కేంద్రం: 1800-309-8800",
    healthTipTitle: "ఈరోజు ఆరోగ్య సూచన",
    healthTipContent: "ఎండకాలంలో వచ్చే కడుపు సమస్యలను నివారించడానికి రాగి పాత్రలో నిల్వ ఉంచిన నీరు లేదా కాచి చల్లార్చిన నీరు త్రాగండి.",
    medicineSearchPlaceholder: "మందుల పేరుతో వెతకండి (ఉదా: Paracetamol)...",
    allCategories: "అన్ని రకాలు",
    feverPain: "జ్వరం & నొప్పుల నివారణ",
    coldAllergy: "జలుబు & అలర్జీలు",
    stomachGas: "కడుపు నొప్పి & గ్యాస్",
    vitaminsNutrition: "విటమిన్లు & బలం మందులు",
    firstAid: "ప్రథమ చికిత్స మందులు",
    bloodPressure: "రక్తపోటు / BP మందులు",
    diabetesCare: "షుగర్ / డయాబెటిస్ మందులు",
    genericName: "జెనరిక్ పేరు",
    dosage: "మోతాదు / Dosage",
    price: "ధర / Price",
    rs: "₹",
    addToCart: "బ్యాగులో వేయి / Add to Cart",
    added: "చేర్చబడింది / Added",
    outOfStock: "నిల్వ లేదు / Out of Stock",
    cartTitle: "మీ మందుల బ్యాగ్",
    emptyCart: "మీ బ్యాగ్ ఖాళీగా ఉంది. ఆరోగ్యంగా ఉండటానికి మందులను ఆర్డర్ చేయండి!",
    itemTotal: "మందుల మొత్తం ధర",
    deliveryCharges: "డెలివరీ ఛార్జీలు",
    free: "ఉచితం / FREE",
    totalPayable: "మొత్తం చెల్లించవలసిన ధర",
    proceedCheckout: "ఆర్డర్ చేయడానికి ముందుకు సాగండి",
    checkoutTitle: "డెలివరీ చిరునామా మరియు చెల్లింపు వివరాలు",
    fullName: "పూర్తి పేరు",
    village: "గ్రామం / పట్టణం",
    panchayat: "గ్రామ పంచాయతీ",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    pincode: "పిన్ కోడ్ (6 అంకెలు)",
    selectPayment: "చెల్లింపు పద్ధతి ఎంచుకోండి",
    upiPay: "UPI (Google Pay / PhonePe / Paytm)",
    cardPay: "ఏటీఎం కార్డు / డెబిట్ కార్డు",
    walletPay: "మొబైల్ వాలెట్",
    codPay: "నగదు రూపంలో చెల్లింపు (COD)",
    placeOrder: "ఆర్డర్ ఖరారు చేయండి",
    paymentModalTitle: "చెల్లింపు గేట్ వే",
    paymentModalBody: "ఈ క్యూఆర్ కోడ్ స్కాన్ చేసి పేమెంట్ పూర్తి చేయండి లేదా సిమ్యులేషన్ కోసం 'సక్సెస్' బటన్ నొక్కండి.",
    scanQrCode: "పేమెంట్ కోసం క్యూఆర్ స్కాన్ చేయండి",
    simulatedSuccess: "విజయవంతం / Success",
    simulatedFail: "విఫలం / Fail",
    orderSuccessTitle: "ఆర్డర్ విజయవంతంగా పూర్తయింది!",
    orderSuccessDesc: "మందులు త్వరలోనే మీ గ్రామానికి చేరుకుంటాయి. 'నా ఆర్డర్లు' విభాగంలో స్థితిని చూడవచ్చు.",
    close: "మూసివేయి / Close",
    orderHistory: "ఆర్డర్ల చరిత్ర",
    noOrders: "మీరు ఇంకా ఎలాంటి ఆర్డర్లు చేయలేదు.",
    orderId: "ఆర్డర్ ఐడీ",
    status: "స్థితి / Status",
    payment: "చెల్లింపు / Payment",
    items: "వస్తువులు / Items",
    address: "చిరునామా / Address",
    downloadInvoice: "రసీదు డౌన్ లోడ్ చేసుకోండి",
    orderedState: "ఆర్డర్ చేయబడింది",
    dispatchedState: "కేంద్రం నుండి పంపబడింది",
    outForDeliveryState: "డెలివరీకి వచ్చింది",
    deliveredState: "చేరింది",
    consultTitle: "ఆన్లైన్ డాక్టర్ సంప్రదింపులు",
    consultSubtitle: "నగరాల్లోని నిపుణులైన డాక్టర్లతో మీ ఇంట్లోనే ఉండి వీడియో లేదా ఆడియో ద్వారా మాట్లాడండి.",
    availableDoctors: "ఈరోజు అందుబాటులో ఉన్న డాక్టర్లు",
    languagesSpoken: "మాట్లాడే భాషలు",
    consultationFee: "డాక్టర్ ఫీజు",
    bookNow: "బుక్ చేయండి / Book",
    consultationHistory: "గత సంప్రదింపుల వివరాలు",
    noConsultations: "ఎలాంటి సంప్రదింపుల రికార్డులు లేవు.",
    startVideoCall: "వీడియో కాల్ లో చేరండి",
    viewPrescription: "ప్రిస్క్రిప్షన్ డౌన్ లోడ్ చేయండి",
    connecting: "డాక్టర్ తో కనెక్ట్ అవుతోంది... దయచేసి కెమెరా, మైక్రోఫోన్ అనుమతించండి.",
    hangUp: "కాల్ ముగించు / End Call",
    patientName: "రోగి పేరు",
    selectPatient: "రోగిని ఎంచుకోండి",
    describeSymptom: "మీ సమస్యలను తెలియజేయండి (ఉదా: 2 రోజులుగా జ్వరం ఉంది)",
    symptomPlaceholder: "మీ సమస్యలను ఇక్కడ రాయండి...",
    payAndStartCall: "ఫీజు చెల్లించి కాల్ ప్రారంభించండి",
    subTitle: "గ్రామీణ ఆరోగ్య పథకాలు",
    subSubtitle: "నెలకి కేవలం ₹49 లతో మీ కుటుంబానికి ఆరోగ్య భరోసా కల్పించండి.",
    freeDelivery: "అపరిమిత ఉచిత మందుల డెలివరీ",
    freeConsults: "ఉచిత డాక్టర్ సంప్రదింపులు",
    villageDiscount: "మందులపై అదనంగా 10% తగ్గింపు",
    subscribeBtn: "సబ్ స్క్రైబ్ చేసుకోండి",
    currentPlan: "ప్రస్తుత ప్లాన్",
    active: "క్రియాశీలంగా ఉంది / Active",
    upgrade: "ప్లాన్ మార్చండి / Upgrade",
    planBasic: "గ్రామ రక్ష (బేసిక్)",
    planFamily: "కుటుంబ కళ్యాణ్ (స్టాండర్డ్)",
    planVillage: "గ్రామ సమాజం (ప్రీమియం)",
    planNone: "ఉచిత సేవ (వాడినదానికి మాత్రమే చెల్లింపు)",
    delTitle: "డెలివరీ పార్ట్నర్ గా చేరండి",
    delSubtitle: "మీ గ్రామంలోని వారికి మందులు అందిస్తూ, స్థిరమైన ఆదాయం సంపాదించండి.",
    requirements: "అర్హతలు (Requirements)",
    benefits: "లాభాలు & ఆదాయం (Benefits)",
    reqAge: "వయస్సు: 18 సంవత్సరాలు లేదా అంతకంటే ఎక్కువ ఉండాలి",
    reqVehicle: "వాహనం: సొంత సైకిల్ లేదా మోటార్ సైకిల్ ఉండాలి",
    reqLicense: "లైసెన్స్: ద్విచక్ర వాహనం నడపడానికి డ్రైవింగ్ లైసెన్స్ ఉండాలి",
    reqPhone: "స్మార్ట్ ఫోన్: ఇంటర్నెట్ సదుపాయం గల ఆండ్రాయిడ్ మొబైల్",
    reqArea: "స్థానిక పరిజ్ఞానం: చుట్టుపక్కల గ్రామాలు మరియు దారులపై అవగాహన",
    benHours: "సౌకర్యవంతమైన వేళలు: మీకు నచ్చిన సమయంలో పని చేయవచ్చు",
    benPayouts: "వారపు చెల్లింపులు: నేరుగా మీ బ్యాంక్ ఖాతాకే డబ్బులు జమ",
    benIncentives: "అదనపు ఆదాయం: రాత్రి వేళల్లో లేదా వర్షంలో డెలివరీలకు ప్రత్యేక బోనస్",
    benSupport: "ప్రమాద బీమా మరియు వైద్య సదుపాయం",
    registerFormTitle: "రిజిస్ట్రేషన్ ఫారమ్ (Form)",
    regName: "పూర్తి పేరు",
    regPhone: "ఫోన్ నెంబర్",
    regVehicleType: "వాహనం రకం",
    regVillage: "పని చేయదలచిన గ్రామం / బ్లాక్",
    regLicenseNo: "డ్రైవింగ్ లైసెన్స్ నెంబర్",
    regSubmit: "అప్లికేషన్ సమర్పించు",
    regSuccess: "ధన్యవాదాలు! మా బ్లాక్ కోఆర్డినేటర్ 24 గంటల్లో మిమ్మల్ని సంప్రదిస్తారు.",
    searchTitle: "ఫొటోతో మందులను వెతకండి",
    searchSubtitle: "మందుల ప్యాకెట్ లేదా ప్రిస్క్రిప్షన్ ఫొటోను అప్ లోడ్ చేయండి, మా సిస్టమ్ దానిని గుర్తిస్తుంది.",
    capturePhoto: "కెమెరాతో ఫొటో తీయండి",
    uploadPhoto: "ఫొటో అప్ లోడ్ చేయండి",
    takePhoto: "ఫొటో తీయండి",
    retakePhoto: "మళ్ళీ ఫొటో తీయండి",
    selectFromGallery: "గ్యాలరీ నుండి ఎంచుకోండి",
    validationSize: "ఫైల్ సైజు 5MB కంటే తక్కువ ఉండాలి.",
    validationType: "JPG, JPEG మరియు PNG ఫార్మాట్లలోని ఫొటోలు మాత్రమే అనుమతించబడతాయి.",
    scanning: "ఫొటోను స్కాన్ చేస్తున్నాము... మందు పేరును గుర్తిస్తున్నాము...",
    matchingMeds: "మా వద్ద లభ్యతగా ఉన్న సరిపోలే మందులు:",
    noMatch: "సరిపోలే మందులు ఏవీ లభించలేదు. దయచేసి సహాయ కేంద్రాన్ని లేదా డాక్టర్ ని సంప్రదించండి.",
    translateTitle: "భాషా అనువాదం అవసరమా?",
    translateBody: "డాక్టర్ రాసిన ఇంగ్లీష్ ప్రిస్క్రిప్షన్ ని మీ మొబైల్ లోని 'Google Translate' యాప్ ద్వారా కెమెరాను చూపించి మీ సొంత భాషలో వెంటనే చూడవచ్చు.",
    translateStep1: "1. ప్లే స్టోర్ నుండి Google Translate యాప్ ని ఇన్ స్టాల్ చేయండి.",
    translateStep2: "2. యాప్ ఓపెన్ చేసి English నుండి Telugu కి ఎంచుకోండి.",
    translateStep3: "3. యాప్ లోని 'Camera' గుర్తును నొక్కి మీ ప్రిస్క్రిప్షన్ పేపర్ పై చూపించండి.",
    familyTitle: "నా కుటుంబ ఖాతా / Family Account",
    familySubtitle: "ఒకే ఖాతా కింద మీ పిల్లలు, భార్య/భర్త మరియు తల్లిదండ్రుల ఆరోగ్య ప్రొఫైల్స్ ని నిర్వహించండి.",
    addMember: "కుటుంబ సభ్యుడిని చేర్చు",
    relationship: "సంబంధం / Relationship",
    ageYears: "వయస్సు (సంవత్సరాలలో)",
    gender: "లింగము / Gender",
    medicalHistory: "ఆరోగ్య చరిత్ర (అలర్జీలు, దీర్ఘకాలిక సమస్యలు)",
    relationSelf: "స్వంతం",
    relationSpouse: "భార్య / భర్త",
    relationChild: "పిల్లలు",
    relationParent: "తల్లి / తండ్రి",
    relationSibling: "సహోదరుడు / సహోదరి",
    relationOther: "ఇతర",
    noFamily: "ఇంకా ఎలాంటి కుటుంబ సభ్యులను చేర్చలేదు.",
    removeMember: "సభ్యుడిని తొలగించు"
  },
  ta: {
    emergencyBar: "🚨 அவசர மருத்துவ சேவை & ஆம்புலன்ஸ்: 108 | கட்டணமில்லா எண்: 1800-309-8800",
    navHome: "முகப்பு / Home",
    navMedicines: "மருந்துகள் / Medicines",
    navConsult: "மருத்துவர் ஆலோசனை",
    navSubscription: "ஆரோக்கிய திட்டங்கள் / Plans",
    navDelivery: "டெலிவரி பார்ட்னர்",
    navOrders: "எனது ஆர்டர்கள் / Orders",
    navSearch: "படம் மூலம் தேடுக",
    navFamily: "குடும்ப கணக்குகள்",
    logout: "வெளியேறு / Logout",
    cart: "மருந்து பை / Cart",
    loginTitle: "ரூரல்கேர் உங்களை வரவேற்கிறது",
    loginSubtitle: "கிராமப்புற மக்களுக்கான ஆன்லைன் மருத்துவர் மற்றும் மருந்து விநியோக சேவை",
    phoneLabel: "தொலைபேசி எண்",
    nameLabel: "உங்கள் பெயர்",
    loginBtn: "ஒடிபி சரிபார்ப்பு",
    phonePlaceholder: "10 இலக்க மொபைல் எண்ணை உள்ளிடவும்",
    namePlaceholder: "உங்கள் முழு பெயரை உள்ளிடவும்",
    requiredFields: "தயவுசெய்து உங்கள் பெயர் மற்றும் தொலைபேசி எண்ணை உள்ளிடவும்.",
    welcome: "வணக்கம், ரூரல்கேர் உங்களை வரவேற்கிறது",
    homeSubtitle: "தரமான மருத்துவர்கள் மற்றும் மருந்துகளை நேரடியாக உங்கள் கிராமத்திற்கே கொண்டு சேர்க்கிறோம்.",
    callDoctorNow: "மருத்துவரை உடனே அணுகவும்",
    orderMedsNow: "மருந்துகளை ஆர்டர் செய்ய",
    imageSearchNow: "படம் மூலம் மருந்தை தேட",
    manageFamilyNow: "குடும்ப உறுப்பினர்களை சேர்க்க",
    emergencyContact: "அவசர எண்கள்",
    ambulance108: "அவசர ஆம்புலன்ஸ்: 108",
    ruralCareTollFree: "ரூரல்கேர் உதவி மையம்: 1800-309-8800",
    healthTipTitle: "இன்றைய ஆரோக்கிய குறிப்பு",
    healthTipContent: "கோடைகாலத்தில் வயிற்று உபாதைகளைத் தடுக்க செப்புப் பாத்திரத்தில் சேமிக்கப்பட்ட நீர் அல்லது காய்ச்சி வடிகட்டிய நீரைக் குடிக்கவும்.",
    medicineSearchPlaceholder: "மருந்துகளை தேடுக (எ.கா: Paracetamol)...",
    allCategories: "அனைத்து பிரிவுகள்",
    feverPain: "காய்ச்சல் & வலி நிவாரணிகள்",
    coldAllergy: "சளி & ஒவ்வாமை மருந்துகள்",
    stomachGas: "வயிற்று வலி & வாயுத்தொல்லை",
    vitaminsNutrition: "வைட்டமின்கள் & சத்து மருந்துகள்",
    firstAid: "முதலுதவி மருந்துகள்",
    bloodPressure: "இரத்த அழுத்தம் / BP மருந்துகள்",
    diabetesCare: "சர்க்கரை நோய் / நீரிழிவு மருந்துகள்",
    genericName: "ஜெனரிக் பெயர்",
    dosage: "அளவு / Dosage",
    price: "விலை / Price",
    rs: "₹",
    addToCart: "பையில் சேர்க்க / Add to Cart",
    added: "சேர்க்கப்பட்டது / Added",
    outOfStock: "கைவசம் இல்லை / Out of Stock",
    cartTitle: "உங்கள் மருந்து பை",
    emptyCart: "உங்கள் பை காலியாக உள்ளது. ஆரோக்கியமாக இருக்க மருந்துகளை ஆர்டர் செய்யுங்கள்!",
    itemTotal: "மருந்துகளின் மொத்த விலை",
    deliveryCharges: "டெலிவரி கட்டணம்",
    free: "இலவசம் / FREE",
    totalPayable: "மொத்தம் செலுத்த வேண்டிய தொகை",
    proceedCheckout: "ஆர்டர் செய்ய தொடரவும்",
    checkoutTitle: "டெலிவரி முகவரி மற்றும் கட்டணம்",
    fullName: "முழு பெயர்",
    village: "கிராமம் / நகரம்",
    panchayat: "கிராம பஞ்சாயத்து",
    district: "மாவட்டம்",
    state: "மாநிலம்",
    pincode: "அஞ்சல் குறியீடு (6 இலக்கங்கள்)",
    selectPayment: "கட்டண முறையைத் தேர்வு செய்யவும்",
    upiPay: "UPI (Google Pay / PhonePe / Paytm)",
    cardPay: "ஏடிஎம் கார்டு / டெபிட் கார்டு",
    walletPay: "மொபைல் வாலெட்",
    codPay: "பணம் செலுத்திப் பெறுதல் (COD)",
    placeOrder: "ஆர்டரை உறுதி செய்க",
    paymentModalTitle: "கட்டணம் செலுத்தும் முறை",
    paymentModalBody: "இந்த கியூஆர் கோடை ஸ்கேன் செய்து பணம் செலுத்தவும் அல்லது சோதனைக்காக 'சக்சஸ்' பட்டனை அழுத்தவும்.",
    scanQrCode: "பணம் செலுத்த கியூஆர் கோடை ஸ்கேன் செய்க",
    simulatedSuccess: "வெற்றி / Success",
    simulatedFail: "தோல்வி / Fail",
    orderSuccessTitle: "ஆர்டர் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!",
    orderSuccessDesc: "மருந்துகள் விரைவில் உங்கள் கிராமத்திற்கு வந்து சேரும். 'எனது ஆர்டர்கள்' பகுதியில் நிலவரத்தை அறியலாம்.",
    close: "மூடுக / Close",
    orderHistory: "ஆர்டர் வரலாறு",
    noOrders: "நீங்கள் இன்னும் ஆர்டர்கள் எதுவும் செய்யவில்லை.",
    orderId: "ஆர்டர் ஐடி",
    status: "நிலை / Status",
    payment: "கட்டணம் / Payment",
    items: "பொருட்கள் / Items",
    address: "முகவரி / Address",
    downloadInvoice: "ரசீதை பதிவிறக்க",
    orderedState: "ஆர்டர் செய்யப்பட்டுள்ளது",
    dispatchedState: "மையத்திலிருந்து அனுப்பப்பட்டது",
    outForDeliveryState: "டெலிவரிக்கு வந்துள்ளது",
    deliveredState: "விநியோகிக்கப்பட்டது",
    consultTitle: "ஆன்லைன் மருத்துவர் ஆலோசனை",
    consultSubtitle: "நகரங்களில் உள்ள சிறந்த மருத்துவர்களுடன் உங்கள் வீட்டிலிருந்தே வீடியோ அல்லது ஆடியோ மூலம் பேசுங்கள்.",
    availableDoctors: "இன்று இருக்கும் மருத்துவர்கள்",
    languagesSpoken: "பேசும் மொழிகள்",
    consultationFee: "மருத்துவர் கட்டணம்",
    bookNow: "பதிவு செய்க / Book",
    consultationHistory: "ஆலோசனைகளின் வரலாறு",
    noConsultations: "முந்தைய ஆலோசனைகள் எதுவும் இல்லை.",
    startVideoCall: "வீடியோ அழைப்பில் இணையவும்",
    viewPrescription: "மருந்து சீட்டை பதிவிறக்குக",
    connecting: "மருத்துவருடன் இணைப்பு ஏற்படுத்தப்படுகிறது... கேமரா மற்றும் மைக்கை இயக்கவும்.",
    hangUp: "அழைப்பை முடிக்க / End Call",
    patientName: "நோயாளி பெயர்",
    selectPatient: "நோயாளியை தேர்வு செய்க",
    describeSymptom: "உங்கள் உடல் உபாதைகளை எழுதவும் (எ.கா: 2 நாட்களாக காய்ச்சல்)",
    symptomPlaceholder: "உங்கள் பிரச்சனைகளை இங்கே எழுதவும்...",
    payAndStartCall: "கட்டணம் செலுத்தி அழைப்பைத் தொடங்கவும்",
    subTitle: "கிராமப்புற குடும்ப ஆரோக்கிய திட்டங்கள்",
    subSubtitle: "மாதம் ₹49 முதல் தொடங்கும் திட்டங்களுடன் உங்கள் குடும்பத்திற்கு பாதுகாப்பு அளிக்கவும்.",
    freeDelivery: "வரம்பற்ற இலவச மருந்து டெலிவரி",
    freeConsults: "இலவச மருத்துவர் ஆலோசனை",
    villageDiscount: "மருந்துகளுக்கு கூடுதல் 10% தள்ளுபடி",
    subscribeBtn: "இப்போதே சேரவும்",
    currentPlan: "தற்போதைய திட்டம்",
    active: "செயலில் உள்ளது / Active",
    upgrade: "திட்டத்தை மாற்றவும் / Upgrade",
    planBasic: "கிராம காப்பு (பேசிக்)",
    planFamily: "குடும்ப நலன் (ஸ்டாண்டர்ட்)",
    planVillage: "கிராம சமூகம் (பிரிமியம்)",
    planNone: "இலவச சேவை (பயன்படுத்துவதற்கு மட்டும் கட்டணம்)",
    delTitle: "டெலிவரி பார்ட்னராக இணையுங்கள்",
    delSubtitle: "உங்கள் கிராமத்தினருக்கு மருந்துகளை வழங்கி, நிலையான வருமானம் ஈட்டுங்கள்.",
    requirements: "தகுதிகள் (Requirements)",
    benefits: "பலன்கள் & வருமானம் (Benefits)",
    reqAge: "வயது: 18 வயது அல்லது அதற்கு மேல் இருக்க வேண்டும்",
    reqVehicle: "வாகனம்: சொந்த சைக்கிள் அல்லது இருசக்கர வாகனம் இருக்க வேண்டும்",
    reqLicense: "உரிமம்: இருசக்கர வாகனத்திற்கான ஓட்டுநர் உரிமம்",
    reqPhone: "ஸ்மார்ட்போன்: இணைய இணைப்பு உள்ள ஆண்ட்ராய்டு மொபைல்",
    reqArea: "உள்ளூர் அறிவு: கிராமங்கள் மற்றும் வழிகள் பற்றிய தெளிவான அறிவு",
    benHours: "நெகிழ்வான வேலை நேரம்: உங்களுக்கு விருப்பமான நேரத்தில் வேலை செய்யலாம்",
    benPayouts: "வாராந்திர வருமானம்: உங்கள் வங்கி கணக்கில் நேரடியாக பணம் செலுத்தப்படும்",
    benIncentives: "கூடுதல் ஊக்கத்தொகை: இரவு நேர அல்லது மழைக்கால டெலிவரிகளுக்கு சிறப்பு போனஸ்",
    benSupport: "விபத்து காப்பீடு மற்றும் மருத்துவ உதவி",
    registerFormTitle: "விண்ணப்ப படிவம் (Form)",
    regName: "முழு பெயர்",
    regPhone: "தொலைபேசி எண்",
    regVehicleType: "வாகன வகை",
    regVillage: "வேலை செய்ய விரும்பும் கிராமம் / ஒன்றியம்",
    regLicenseNo: "ஓட்டுநர் உரிம எண்",
    regSubmit: "விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    regSuccess: "நன்றி! எங்களது ஒருங்கிணைப்பாளர் 24 மணி நேரத்திற்குள் உங்களைத் தொடர்புகொள்வார்.",
    searchTitle: "படம் மூலம் மருந்துகளைத் தேடவும்",
    searchSubtitle: "மருந்து அட்டை அல்லது மருத்துவரின் சீட்டை படம் எடுத்து பதிவேற்றவும், எங்கள் கணினி அதை கண்டறியும்.",
    capturePhoto: "கேமரா மூலம் படம் எடுக்கவும்",
    uploadPhoto: "படம் பதிவேற்றவும்",
    takePhoto: "படம் எடுக்க",
    retakePhoto: "மீண்டும் படம் எடுக்க",
    selectFromGallery: "கேலரியில் இருந்து தேர்ந்தெடுக்க",
    validationSize: "கோப்பு அளவு 5MB க்கும் குறைவாக இருக்க வேண்டும்.",
    validationType: "JPG, JPEG மற்றும் PNG படங்கள் மட்டுமே அனுமதிக்கப்படும்.",
    scanning: "படம் ஸ்கேன் செய்யப்படுகிறது... மருந்தின் பெயரை கண்டறிகிறது...",
    matchingMeds: "கைவசம் உள்ள பொருத்தமான மருந்துகள்:",
    noMatch: "பொருத்தமான மருந்துகள் எதுவும் இல்லை. உதவி மையத்தை அல்லது மருத்துவரை அணுகவும்.",
    translateTitle: "மொழி பெயர்ப்பு தேவையா?",
    translateBody: "ஆங்கிலத்தில் உள்ள மருந்து சீட்டை உங்கள் மொபைலில் உள்ள 'Google Translate' செயலி மூலம் கேமராவை காட்டி உங்கள் சொந்த மொழியில் உடனே பார்க்கலாம்.",
    translateStep1: "1. பிளே ஸ்டோரிலிருந்து Google Translate செயலியை பதிவிறக்கவும்.",
    translateStep2: "2. செயலியை திறந்து English லிருந்து Tamil ஐ தேர்வு செய்யவும்.",
    translateStep3: "3. 'Camera' குறியீட்டை அழுத்தி உங்கள் மருந்து சீட்டின் மேல் காட்டவும்.",
    familyTitle: "எனது குடும்ப கணக்கு / Family Account",
    familySubtitle: "ஒரே கணக்கின் கீழ் உங்கள் குழந்தைகள், மனைவி/கணவர் மற்றும் பெற்றோரின் சுகாதார சுயவிவரங்களை நிர்வகிக்கவும்.",
    addMember: "குடும்ப உறுப்பினரைச் சேர்க்க",
    relationship: "உறவுமுறை / Relationship",
    ageYears: "வயது (ஆண்டுகளில்)",
    gender: "பாலினம் / Gender",
    medicalHistory: "முந்தைய உடல் உபாதைகள் (ஒவ்வாமை, நீண்ட கால வியாதிகள்)",
    relationSelf: "சுய",
    relationSpouse: "மனைவி / கணவர்",
    relationChild: "குழந்தை",
    relationParent: "தாய் / தந்தை",
    relationSibling: "சகோதரர் / சகோதரி",
    relationOther: "இதர",
    noFamily: "குடும்ப உறுப்பினர்கள் யாரும் இன்னும் சேர்க்கப்படவில்லை.",
    removeMember: "உறுப்பினரை நீக்கு"
  },
  ml: {
    emergencyBar: "🚨 അടിയന്തര മരുന്ന് & ആംബുലൻസ് സേവനം: 108 | ടോൾ ഫ്രീ: 1800-309-8800",
    navHome: "ഹോം / Home",
    navMedicines: "മരുന്നുകൾ / Medicines",
    navConsult: "ഡോക്ടർ കൺസൾട്ടേഷൻ",
    navSubscription: "ഹെൽത്ത് പ്ലാൻ / Plans",
    navDelivery: "ഡെലിവറി പാർട്ണർ",
    navOrders: "എന്റെ ഓർഡറുകൾ / Orders",
    navSearch: "ഫോട്ടോ വഴി തിരയുക",
    navFamily: "കുടുംബ അക്കൗണ്ടുകൾ",
    logout: "ലോഗ് ഔട്ട് / Logout",
    cart: "മരുന്ന് ബാഗ് / Cart",
    loginTitle: "റൂറൽ കെയറിലേക്ക് സ്വാഗതം",
    loginSubtitle: "ഗ്രാമീണ മേഖലയ്ക്കായുള്ള ഓൺലൈൻ ഡോക്ടറും മരുന്ന് വിതരണ സേവനവും",
    phoneLabel: "ഫോൺ നമ്പർ",
    nameLabel: "നിങ്ങളുടെ പേര്",
    loginBtn: "ഒടിപി പരിശോധന",
    phonePlaceholder: "10 അക്ക മൊബൈൽ നമ്പർ നൽകുക",
    namePlaceholder: "നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകുക",
    requiredFields: "ദയവായി നിങ്ങളുടെ പേരും ഫോൺ നമ്പറും നൽകുക.",
    welcome: "നമസ്കാരം, റൂറൽ കെയറിലേക്ക് സ്വാഗതം",
    homeSubtitle: "ഗുണനിലവാരമുള്ള ഡോക്ടർമാരെയും മരുന്നുകളെയും നേരിട്ട് നിങ്ങളുടെ ഗ്രാമത്തിൽ എത്തിക്കുന്നു.",
    callDoctorNow: "ഡോക്ടറെ ഉടൻ ബന്ധപ്പെടുക",
    orderMedsNow: "മരുന്നുകൾ ഓർഡർ ചെയ്യുക",
    imageSearchNow: "ഫോട്ടോ ഉപയോഗിച്ച് മരുന്ന് തിരയുക",
    manageFamilyNow: "കുടുംബാംഗങ്ങളെ ചേർക്കുക",
    emergencyContact: "അടിയന്തര നമ്പറുകൾ",
    ambulance108: "അടിയന്തര ആംബുലൻസ്: 108",
    ruralCareTollFree: "റൂറൽ കെയർ ഹെൽപ്പ് ഡെസ്ക്: 1800-309-8800",
    healthTipTitle: "ഇന്നത്തെ ആരോഗ്യ ടിപ്പ്",
    healthTipContent: "വേനൽക്കാലത്ത് വയറ്റിലെ അണുബാധ തടയാൻ ചെമ്പ് പാത്രത്തിൽ സൂക്ഷിച്ച വെള്ളമോ തിളപ്പിച്ചാറ്റിയ വെള്ളമോ കുടിക്കുക.",
    medicineSearchPlaceholder: "മരുന്നുകൾ തിരയുക (ഉദാ: Paracetamol)...",
    allCategories: "എല്ലാ വിഭാഗങ്ങളും",
    feverPain: "പനി & വേദന സംഹാരികൾ",
    coldAllergy: "ജലദോഷം & അലർജി മരുന്നുകൾ",
    stomachGas: "വയറുവേദന & ഗ്യാസ്",
    vitaminsNutrition: "വിറ്റാമിനുകൾ & പോഷകങ്ങൾ",
    firstAid: "പ്രാഥമിക ചികിത്സാ മരുന്നുകൾ",
    bloodPressure: "രക്തസമ്മർദ്ദം / BP മരുന്നുകൾ",
    diabetesCare: "പ്രമേഹ മരുന്നുകൾ",
    genericName: "ജനറിക് പേര്",
    dosage: "അളവ് / Dosage",
    price: "വില / Price",
    rs: "₹",
    addToCart: "ബാഗിലേക്ക് ചേർക്കുക / Add to Cart",
    added: "ചേർത്തു / Added",
    outOfStock: "ലഭ്യമല്ല / Out of Stock",
    cartTitle: "നിങ്ങളുടെ മരുന്ന് ബാഗ്",
    emptyCart: "നിങ്ങളുടെ ബാഗ് ശൂന്യമാണ്. ആരോഗ്യത്തോടെയിരിക്കാൻ മരുന്നുകൾ ഓർഡർ ചെയ്യൂ!",
    itemTotal: "മരുന്നുകളുടെ ആകെ വില",
    deliveryCharges: "ഡെലിവറി ചാർജ്ജ്",
    free: "സൗജന്യം / FREE",
    totalPayable: "ആകെ നൽകേണ്ട തുക",
    proceedCheckout: "ഓർഡർ ചെയ്യാൻ തുടരുക",
    checkoutTitle: "ഡെലിവറി വിലാസവും പണമടയ്ക്കലും",
    fullName: "പൂർണ്ണ നാമം",
    village: "ഗ്രാമം / നഗരം",
    panchayat: "ഗ്രാമപഞ്ചായത്ത്",
    district: "ജില്ല",
    state: "സംസ്ഥാനം",
    pincode: "പിൻ കോഡ് (6 അക്കങ്ങൾ)",
    selectPayment: "പണമടയ്ക്കാനുള്ള രീതി തിരഞ്ഞെടുക്കുക",
    upiPay: "UPI (Google Pay / PhonePe / Paytm)",
    cardPay: "എടിഎം കാർഡ് / ഡെബിറ്റ് കാർഡ്",
    walletPay: "മൊബൈൽ വാലറ്റ്",
    codPay: "ക്യാഷ് ഓൺ ഡെലിവറി (COD)",
    placeOrder: "ഓർഡർ സ്ഥിരീകരിക്കുക",
    paymentModalTitle: "പണമടയ്ക്കൽ രീതി",
    paymentModalBody: "ഈ ക്യുആർ കോഡ് സ്കാൻ ചെയ്ത് പണമടയ്ക്കുക അല്ലെങ്കിൽ പരീക്ഷിക്കുന്നതിനായി 'സക്സസ്' ബട്ടൺ അമർത്തുക.",
    scanQrCode: "പണമടയ്ക്കാൻ ക്യുആർ കോഡ് സ്കാൻ ചെയ്യുക",
    simulatedSuccess: "വിജയം / Success",
    simulatedFail: "പരാജയം / Fail",
    orderSuccessTitle: "ഓർഡർ വിജയകരമായി സമർപ്പിച്ചു!",
    orderSuccessDesc: "മരുന്നുകൾ ഉടൻ തന്നെ നിങ്ങളുടെ ഗ്രാമത്തിൽ എത്തും. 'എന്റെ ഓർഡറുകൾ' എന്നതിൽ ഇതിന്റെ സ്ഥിതി പരിശോധിക്കാം.",
    close: "അടയ്ക്കുക / Close",
    orderHistory: "ഓർഡർ ഹിസ്റ്ററി",
    noOrders: "നിങ്ങൾ ഇതുവരെ ഓർഡറുകൾ ഒന്നും നൽകിയിട്ടില്ല.",
    orderId: "ഓർഡർ ഐഡി",
    status: "നില / Status",
    payment: "പേയ്മെന്റ് / Payment",
    items: "ഇനങ്ങൾ / Items",
    address: "വിലാസം / Address",
    downloadInvoice: "രസീത് ഡൗൺലോഡ് ചെയ്യുക",
    orderedState: "ഓർഡർ നൽകി",
    dispatchedState: "കേന്ദ്രത്തിൽ നിന്ന് അയച്ചു",
    outForDeliveryState: "ഡെലിവറിക്കായി എത്തിയിട്ടുണ്ട്",
    deliveredState: "ലഭിച്ചു",
    consultTitle: "ഓൺലൈൻ ഡോക്ടർ കൺസൾട്ടേഷൻ",
    consultSubtitle: "നഗരങ്ങളിലെ പ്രമുഖ ഡോക്ടർമാരുമായി നിങ്ങളുടെ വീട്ടിലിരുന്ന് വീഡിയോ അല്ലെങ്കിൽ ഓഡിയോ വഴി സംസാരിക്കാം.",
    availableDoctors: "ഇന്ന് ലഭ്യമായ ഡോക്ടർമാർ",
    languagesSpoken: "സംസാരിക്കുന്ന ഭാഷകൾ",
    consultationFee: "ഡോക്ടറുടെ ഫീസ്",
    bookNow: "ബുക്ക് ചെയ്യുക / Book",
    consultationHistory: "മുൻ കൺസൾട്ടേഷനുകൾ",
    noConsultations: "മുൻ കൺസൾട്ടേഷൻ റെക്കോർഡുകൾ ഒന്നും തന്നെയില്ല.",
    startVideoCall: "വീഡിയോ കോളിൽ ചേരുക",
    viewPrescription: "കുറിപ്പടി (പ്രിസ്ക്രിപ്ഷൻ) ഡൗൺലോഡ് ചെയ്യുക",
    connecting: "ഡോക്ടറുമായി ബന്ധിപ്പിക്കുന്നു... ദയവായി ക്യാമറയും മൈക്കും പ്രവർത്തനക്ഷമമാക്കുക.",
    hangUp: "കോൾ അവസാനിപ്പിക്കുക / End Call",
    patientName: "രോഗിയുടെ പേര്",
    selectPatient: "രോഗിയെ തിരഞ്ഞെടുക്കുക",
    describeSymptom: "നിങ്ങളുടെ അസുഖ ലക്ഷണങ്ങൾ വിവരിക്കുക (ഉദാ: 2 ദിവസമായി പനി)",
    symptomPlaceholder: "നിങ്ങളുടെ ബുദ്ധിമുട്ടുകൾ ഇവിടെ എഴുതുക...",
    payAndStartCall: "ഫീസ് അടച്ച് കോൾ ആരംഭിക്കുക",
    subTitle: "ഗ്രാമീണ ആരോഗ്യ പദ്ധതികൾ",
    subSubtitle: "പ്രതിമാസം വെറും ₹49 രൂപ മുതൽ ആരംഭിക്കുന്ന പ്ലാനുകളിലൂടെ നിങ്ങളുടെ കുടുംബത്തെ സംരക്ഷിക്കുക.",
    freeDelivery: "പരിധിയില്ലാത്ത സൌജന്യ മരുന്ന് വിതരണം",
    freeConsults: "സൌജന്യ ഡോക്ടർ കൺസൾട്ടേഷൻ",
    villageDiscount: "മരുന്നുകൾക്ക് 10% അധിക കിഴിവ്",
    subscribeBtn: "ഇപ്പോൾ സബ്സ്ക്രൈബ് ചെയ്യുക",
    currentPlan: "നിലവിലെ പ്ലാൻ",
    active: "സജീവമാണ് / Active",
    upgrade: "പ്ലാൻ മാറ്റുക / Upgrade",
    planBasic: "ഗ്രാമ രക്ഷ (ബേസിക്)",
    planFamily: "കുടുംബ സുരക്ഷ (സ്റ്റാൻഡേർഡ്)",
    planVillage: "ഗ്രാമ കൂട്ടായ്മ (പ്രീമിയം)",
    planNone: "സൌജന്യ സേവനം (ആവശ്യത്തിന് മാത്രം പണം നൽകുക)",
    delTitle: "ഡെലിവറി പാർട്ണറാകൂ",
    delSubtitle: "നിങ്ങളുടെ ഗ്രാമത്തിൽ മരുന്നുകൾ എത്തിക്കൂ, ആഴ്ചതോറും വരുമാനം നേടൂ.",
    requirements: "യോഗ്യതകൾ (Requirements)",
    benefits: "നേട്ടങ്ങളും വരുമാനവും (Benefits)",
    reqAge: "പ്രായം: 18 വയസ്സോ അതിൽ കൂടുതലോ ആയിരിക്കണം",
    reqVehicle: "വാഹനം: സ്വന്തമായി സൈക്കിളോ ഇരുചക്ര വാഹനമോ ഉണ്ടായിരിക്കണം",
    reqLicense: "ലൈസൻസ്: ഇരുചക്ര വാഹനത്തിനുള്ള ലൈസൻസ് ഉണ്ടായിരിക്കണം",
    reqPhone: "സ്മാർട്ട്ഫോൺ: ഇന്റർനെറ്റ് കണക്ഷനുള്ള ആൻഡ്രോയിഡ് മൊബൈൽ",
    reqArea: "പ്രാദേശിക അറിവ്: ഗ്രാമങ്ങളെയും വഴികളെയും കുറിച്ചുള്ള വ്യക്തമായ ധാരണ",
    benHours: "നിങ്ങളുടെ സൗകര്യമുള്ള സമയം: എപ്പോൾ വേണമെങ്കിലും ജോലി ചെയ്യാം",
    benPayouts: "പ്രതിവാര പേയ്‌മെന്റുകൾ: പണം നേരിട്ട് നിങ്ങളുടെ ബാങ്ക് അക്കൗണ്ടിലേക്ക് എത്തും",
    benIncentives: "അധിക ഇൻസെന്റീവുകൾ: രാത്രിയിലോ മഴയിലോ ഉള്ള ഡെലിവറികൾക്ക് പ്രത്യേക ബോണസ്",
    benSupport: "അപകട ഇൻഷുറൻസും മെഡിക്കൽ സഹായവും",
    registerFormTitle: "അപേക്ഷ ഫോം (Form)",
    regName: "പൂർണ്ണ നാമം",
    regPhone: "ഫോൺ നമ്പർ",
    regVehicleType: "വാഹനത്തിന്റെ തരം",
    regVillage: "ജോലി ചെയ്യാൻ ആഗ്രഹിക്കുന്ന ഗ്രാമം / ബ്ലോക്ക്",
    regLicenseNo: "ഡ്രൈവിംഗ് ലൈസൻസ് നമ്പർ",
    regSubmit: "അപേക്ഷ സമർപ്പിക്കുക",
    regSuccess: "നന്ദി! ഞങ്ങളുടെ ബ്ലോക്ക് കോർഡിനേറ്റർ 24 മണിക്കൂറിനുള്ളിൽ നിങ്ങളെ ബന്ധപ്പെടും.",
    searchTitle: "ഫോട്ടോ ഉപയോഗിച്ച് മരുന്ന് തിരയുക",
    searchSubtitle: "മരുന്ന് അട്ടയുടെയോ കുറിപ്പടിയുടെയോ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക, ഞങ്ങളുടെ സിസ്റ്റം അത് തിരിച്ചറിയും.",
    capturePhoto: "ക്യാമറ വഴി ഫോട്ടോ എടുക്കുക",
    uploadPhoto: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
    takePhoto: "ഫോട്ടോ എടുക്കുക",
    retakePhoto: "വീണ്ടും ഫോട്ടോ എടുക്കുക",
    selectFromGallery: "ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക",
    validationSize: "ഫയൽ സൈസ് 5MB-ൽ കുറവായിരിക്കണം.",
    validationType: "JPG, JPEG, PNG ചിത്രങ്ങൾ മാത്രമേ അനുവദിക്കൂ.",
    scanning: "ചിത്രം സ്കാൻ ചെയ്യുന്നു... മരുന്നിന്റെ പേര് കണ്ടെത്തുന്നു...",
    matchingMeds: "ലഭ്യമായ അനുയോജ്യമായ മരുന്നുകൾ:",
    noMatch: "അനുയോജ്യമായ മരുന്നുകൾ ഒന്നും കണ്ടെത്താനായില്ല. ഹെൽപ്പ് ഡെസ്കിനെയോ ഡോക്ടറെയോ സമീപിക്കുക.",
    translateTitle: "ഭാഷാ വിവർത്തനം ആവശ്യമുണ്ടോ?",
    translateBody: "ഇംഗ്ലീഷിലുള്ള മരുന്ന് കുറിപ്പടി നിങ്ങളുടെ മൊബൈലിലെ 'Google Translate' ആപ്പ് ഉപയോഗിച്ച് ക്യാമറ കാണിച്ച് നിങ്ങളുടെ സ്വന്തം ഭാഷയിൽ ഉടൻ തന്നെ കാണാം.",
    translateStep1: "1. പ്ലേ സ്റ്റോറിൽ നിന്ന് Google Translate ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക.",
    translateStep2: "2. ആപ്പ് തുറന്ന് English-ൽ നിന്നും Malayalam തിരഞ്ഞെടുക്കുക.",
    translateStep3: "3. 'Camera' ചിഹ്നം അമർത്തി നിങ്ങളുടെ മരുന്ന് കുറിപ്പടിക്ക് നേരെ കാണിക്കുക.",
    familyTitle: "എന്റെ കുടുംബ അക്കൗണ്ട് / Family Account",
    familySubtitle: "ഒരൊറ്റ അക്കൗണ്ടിന് കീഴിൽ നിങ്ങളുടെ കുട്ടികൾ, പങ്കാളി, മാതാപിതാക്കൾ എന്നിവരുടെ ആരോഗ്യ വിവരങ്ങൾ കൈകാര്യം ചെയ്യുക.",
    addMember: "കുടുംബാംഗത്തെ ചേർക്കുക",
    relationship: "ബന്ധം / Relationship",
    ageYears: "പ്രായം (വർഷത്തിൽ)",
    gender: "ലിംഗം / Gender",
    medicalHistory: "മുൻകാല രോഗവിവരങ്ങൾ (അലർജി, ആസ്ത്മ, പ്രമേഹം തുടങ്ങിയവ)",
    relationSelf: "സ്വന്തം",
    relationSpouse: "ഭാര്യ / ഭർത്താവ്",
    relationChild: "കുട്ടി",
    relationParent: "അമ്മ / അച്ഛൻ",
    relationSibling: "സഹോദരൻ / സഹോദരി",
    relationOther: "മറ്റുള്ളവ",
    noFamily: "കുടുംബാംഗങ്ങളെ ആരെയും ഇതുവരെ ചേർത്തിട്ടില്ല.",
    removeMember: "അംഗത്തെ നീക്കം ചെയ്യുക"
  },
  kn: {
    emergencyBar: "🚨 ತುರ್ತು ವೈದ್ಯಕೀಯ ಸೇವೆ ಮತ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್: 108 | ಟೋಲ್ ಫ್ರೀ: 1800-309-8800",
    navHome: "ಮುಖಪುಟ / Home",
    navMedicines: "ಔಷಧಿಗಳು / Medicines",
    navConsult: "ವೈದ್ಯರ ಸಲಹೆ / Consult",
    navSubscription: "ಆರೋಗ್ಯ ಯೋಜನೆಗಳು / Plans",
    navDelivery: "ಡೆಲಿವರಿ ಪಾರ್ಟ್ನರ್",
    navOrders: "ನನ್ನ ಆರ್ಡರ್ಗಳು / Orders",
    navSearch: "ಫೋಟೋದಿಂದ ಹುಡುಕಿ",
    navFamily: "ಕುಟುಂಬದ ಖಾತೆಗಳು",
    logout: "ಲಾಗ್ ಔಟ್ / Logout",
    cart: "ಔಷಧಿ ಚೀಲ / Cart",
    loginTitle: "ರೂರಲ್ ಕೇರ್ ಗೆ ಸ್ವಾಗತ",
    loginSubtitle: "ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಿಗಾಗಿ ಆನ್ಲೈನ್ ವೈದ್ಯರು ಮತ್ತು ಔಷಧಿ ವಿತರಣಾ ಸೇವೆ",
    phoneLabel: "ಫೋನ್ ಸಂಖ್ಯೆ",
    nameLabel: "ನಿಮ್ಮ ಹೆಸರು",
    loginBtn: "ಒಟಿಪಿ ಪರಿಶೀಲನೆ",
    phonePlaceholder: "10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಹಾಕಿ",
    namePlaceholder: "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ಹಾಕಿ",
    requiredFields: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.",
    welcome: "ನಮಸ್ಕಾರ, ರೂರಲ್ ಕೇರ್ ಗೆ ಸ್ವಾಗತ",
    homeSubtitle: "ಗುಣಮಟ್ಟದ ವೈದ್ಯಕೀಯ ಸೇವೆ ಮತ್ತು ಔಷಧಿಗಳನ್ನು ನೇರವಾಗಿ ನಿಮ್ಮ ಗ್ರಾಮಕ್ಕೆ ತಲುಪಿಸುತ್ತೇವೆ.",
    callDoctorNow: "ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ",
    orderMedsNow: "ಔಷಧಿ ಆರ್ಡರ್ ಮಾಡಿ",
    imageSearchNow: "ಫೋಟೋ ಮೂಲಕ ಔಷಧಿ ಹುಡುಕಿ",
    manageFamilyNow: "ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ",
    emergencyContact: "ತುರ್ತು ಸಂಪರ್ಕಗಳು",
    ambulance108: "ತುರ್ತು ಆಂಬ್ಯುಲೆನ್ಸ್: 108",
    ruralCareTollFree: "ರೂರಲ್ ಕೇರ್ ಸಹಾಯ ಕೇಂದ್ರ: 1800-309-8800",
    healthTipTitle: "ಇಂದಿನ ಆರೋಗ್ಯ ಸಲಹೆ",
    healthTipContent: "ಬೇಸಿಗೆಯಲ್ಲಿ ಹೊಟ್ಟೆಯ ಸೋಂಕು ತಡೆಗಟ್ಟಲು ತಾಮ್ರದ ಪಾತ್ರೆಯಲ್ಲಿಟ್ಟ ನೀರು ಅಥವಾ ಶುದ್ಧವಾದ ಕಾಯಿಸಿ ಆರಿಸಿದ ನೀರನ್ನು ಕುಡಿಯಿರಿ.",
    medicineSearchPlaceholder: "ಔಷಧಿ ಹುಡುಕಿ (ಉದಾ: Paracetamol)...",
    allCategories: "ಎಲ್ಲಾ ವಿಭಾಗಗಳು",
    feverPain: "ಜ್ವರ & ನೋವು ನಿವಾರಕಗಳು",
    coldAllergy: "ಶೀತ & ಅಲರ್ಜಿ ಔಷಧಿಗಳು",
    stomachGas: "ಹೊಟ್ಟೆನೋವು & ಗ್ಯಾಸ್",
    vitaminsNutrition: "ವಿಟಮಿನ್ಗಳು & ಪೌಷ್ಟಿಕಾಂಶಗಳು",
    firstAid: "ಪ್ರಥಮ ಚಿಕಿತ್ಸಾ ಔಷಧಿಗಳು",
    bloodPressure: "ರಕ್ತದೊತ್ತಡ / BP ಔಷಧಿಗಳು",
    diabetesCare: "ಮಧುಮೇಹ / ಶುಗರ್ ಔಷಧಿಗಳು",
    genericName: "ಜೆನೆರಿಕ್ ಹೆಸರು",
    dosage: "ಮಾತ್ರೆ ಪ್ರಮಾಣ / Dosage",
    price: "ಬೆಲೆ / Price",
    rs: "₹",
    addToCart: "ಚೀಲಕ್ಕೆ ಸೇರಿಸಿ / Add to Cart",
    added: "ಸೇರಿಸಲಾಗಿದೆ / Added",
    outOfStock: "ಖಾಲಿಯಾಗಿದೆ / Out of Stock",
    cartTitle: "ನಿಮ್ಮ ಔಷಧಿ ಚೀಲ",
    emptyCart: "ನಿಮ್ಮ ಚೀಲ ಖಾಲಿಯಾಗಿದೆ. ಆರೋಗ್ಯವಾಗಿರಲು ಔಷಧಿಗಳನ್ನು ಆರ್ಡರ್ ಮಾಡಿ!",
    itemTotal: "ಔಷಧಿಗಳ ಒಟ್ಟು ಬೆಲೆ",
    deliveryCharges: "ಡೆಲಿವರಿ ಶುಲ್ಕ",
    free: "ಉಚಿತ / FREE",
    totalPayable: "ಒಟ್ಟು ಪಾವತಿಸಬೇಕಾದ ಮೊತ್ತ",
    proceedCheckout: "ಖರೀದಿಸಲು ಮುಂದೆ ಸಾಗಿ",
    checkoutTitle: "ತಲುಪಿಸಬೇಕಾದ ವಿಳಾಸ ಮತ್ತು ಪಾವತಿ ವಿವರ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    village: "ಗ್ರಾಮ / ಪಟ್ಟಣ",
    panchayat: "ಗ್ರಾಮ ಪಂಚಾಯತ್",
    district: "ಜಿಲ್ಲೆ",
    state: "ರಾಜ್ಯ",
    pincode: "ಪಿನ್ ಕೋಡ್ (6 ಅಂಕಿಗಳು)",
    selectPayment: "ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    upiPay: "UPI (Google Pay / PhonePe / Paytm)",
    cardPay: "ಎಟಿಎಂ ಕಾರ್ಡ್ / ಡೆಬಿಟ್ ಕಾರ್ಡ್",
    walletPay: "ಮೊಬೈಲ್ ವಾಲೆಟ್",
    codPay: "ತಲುಪಿಸಿದಾಗ ನಗದು ಪಾವತಿ (COD)",
    placeOrder: "ಆರ್ಡರ್ ಖಚಿತಪಡಿಸಿ",
    paymentModalTitle: "ಪಾವತಿ ಗೇಟ್ ವೇ",
    paymentModalBody: "ಈ ಕ್ಯೂಆರ್ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ ಅಥವಾ ಪರೀಕ್ಷಿಸಲು 'ಯಶಸ್ವಿ' ಬಟನ್ ಒತ್ತಿ.",
    scanQrCode: "ಪಾವತಿಗಾಗಿ ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    simulatedSuccess: "ಯಶಸ್ವಿ / Success",
    simulatedFail: "ವಿಫಲ / Fail",
    orderSuccessTitle: "ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಕೆಯಾಗಿದೆ!",
    orderSuccessDesc: "ಔಷಧಿಗಳು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮ ಗ್ರಾಮವನ್ನು ತಲುಪುತ್ತವೆ. 'ನನ್ನ ಆರ್ಡರ್ಗಳು' ವಿಭಾಗದಲ್ಲಿ ಸ್ಥಿತಿಯನ್ನು ನೋಡಬಹುದು.",
    close: "ಮುಚ್ಚಿ / Close",
    orderHistory: "ಆರ್ಡರ್ ಗಳ ಇತಿಹಾಸ",
    noOrders: "ನೀವು ಇನ್ನು ಯಾವುದೇ ಆರ್ಡರ್ ಮಾಡಿಲ್ಲ.",
    orderId: "ಆರ್ಡರ್ ಐಡಿ",
    status: "ಸ್ಥಿತಿ / Status",
    payment: "ಪಾವತಿ / Payment",
    items: "ಸಾಮಗ್ರಿಗಳು / Items",
    address: "ವಿಳಾಸ / Address",
    downloadInvoice: "ರಶೀದಿ ಡೌನ್ ಲೋಡ್ ಮಾಡಿ",
    orderedState: "ಆರ್ಡರ್ ಮಾಡಲಾಗಿದೆ",
    dispatchedState: "ಕೇಂದ್ರದಿಂದ ಕಳುಹಿಸಲಾಗಿದೆ",
    outForDeliveryState: "ಡೆಲಿವರಿಗಾಗಿ ಹೊರಟಿದೆ",
    deliveredState: "ತಲುಪಿಸಲಾಗಿದೆ",
    consultTitle: "ಆನ್ಲೈನ್ ವೈದ್ಯರ ಸಂಪರ್ಕ",
    consultSubtitle: "ನಗರದ ಪ್ರಮುಖ ಆಸ್ಪತ್ರೆಗಳ ಪರಿಣಿತ ವೈದ್ಯರೊಂದಿಗೆ ನಿಮ್ಮ ಮನೆಯಲ್ಲೇ ಕುಳಿತು ವಿಡಿಯೋ ಅಥವಾ ಆಡಿಯೋ ಮೂಲಕ ಮಾತನಾಡಿ.",
    availableDoctors: "ಇಂದು ಲಭ್ಯವಿರುವ ವೈದ್ಯರು",
    languagesSpoken: "ಮಾತನಾಡುವ ಭಾಷೆಗಳು",
    consultationFee: "ವೈದ್ಯರ ಶುಲ್ಕ",
    bookNow: "ಬುಕ್ ಮಾಡಿ / Book",
    consultationHistory: "ಹಿಂದಿನ ಸಂಪರ್ಕಗಳ ವಿವರ",
    noConsultations: "ಯಾವುದೇ ಸಂಪರ್ಕಗಳ ರೆಕಾರ್ಡ್ ಇಲ್ಲ.",
    startVideoCall: "ವಿಡಿಯೋ ಕಾಲ್ ಗೆ ಸೇರಿಕೊಳ್ಳಿ",
    viewPrescription: "ಔಷಧಿ ಚೀಟಿ ಡೌನ್ ಲೋಡ್ ಮಾಡಿ",
    connecting: "ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ... ದಯವಿಟ್ಟು ಕ್ಯಾಮೆರಾ ಮತ್ತು ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿಸಿ.",
    hangUp: "ಕರೆ ಮುಗಿಸಿ / End Call",
    patientName: "ರೋಗಿಯ ಹೆಸರು",
    selectPatient: "ರೋಗಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ",
    describeSymptom: "ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ (ಉದಾ: 2 ದಿನಗಳಿಂದ ಜ್ವರ ಇದೆ)",
    symptomPlaceholder: "ನಿಮ್ಮ ತೊಂದರೆಗಳನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ...",
    payAndStartCall: "ಶುಲ್ಕ ಪಾವತಿಸಿ ಕರೆ ಆರಂಭಿಸಿ",
    subTitle: "ಗ್ರಾಮೀಣ ಕೌಟುಂಬಿಕ ಆರೋಗ್ಯ ಯೋಜನೆಗಳು",
    subSubtitle: "ತಿಂಗಳಿಗೆ ಕೇವಲ ₹49 ರಿಂದ ಆರಂಭವಾಗುವ ಯೋಜನೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ರಕ್ಷಣೆ ನೀಡಿ.",
    freeDelivery: "ಅಪರಿಮಿತ ಉಚಿತ ಔಷಧಿ ಡೆಲಿವರಿ",
    freeConsults: "ಉಚಿತ ವೈದ್ಯರ ಸಂಪರ್ಕ",
    villageDiscount: "ಔಷಧಿಗಳ ಮೇಲೆ ಹೆಚ್ಚುವರಿ 10% ರಿಯಾಯಿತಿ",
    subscribeBtn: "ಚಂದಾದಾರರಾಗಿ / Subscribe",
    currentPlan: "ಸದ್ಯದ ಯೋಜನೆ",
    active: "ಸಕ್ರಿಯವಾಗಿದೆ / Active",
    upgrade: "ಯೋಜನೆ ಬದಲಾಯಿಸಿ / Upgrade",
    planBasic: "ಗ್ರಾಮ ರಕ್ಷೆ (ಬೇಸಿಕ್)",
    planFamily: "ಕುಟುಂಬ ಕಲ್ಯಾಣ (ಸ್ಟ್ಯಾಂಡರ್ಡ್)",
    planVillage: "ಗ್ರಾಮ ಸಮುದಾಯ (ಪ್ರೀಮಿಯಂ)",
    planNone: "ಉಚಿತ ಸೇವೆ (ಬಳಸಿದ್ದಕ್ಕೆ ಮಾತ್ರ ಪಾವತಿ)",
    delTitle: "ಡೆಲಿವರಿ ಪಾರ್ಟ್ನರ್ ಆಗಿ ಸೇರಿ",
    delSubtitle: "ನಿಮ್ಮ ಗ್ರಾಮದ ಜನರಿಗೆ ಔಷಧಿ ತಲುಪಿಸುತ್ತಾ, ಸ್ಥಿರವಾದ ಆದಾಯ ಗಳಿಸಿ.",
    requirements: "ಅರ್ಹತೆಗಳು (Requirements)",
    benefits: "ಲಾಭಗಳು ಮತ್ತು ಆದಾಯ (Benefits)",
    reqAge: "ವಯಸ್ಸು: 18 ವರ್ಷ ಅಥವಾ ಅದಕ್ಕಿಂತ ಹೆಚ್ಚು ಇರಬೇಕು",
    reqVehicle: "ವಾಹನ: ಸ್ವಂತ ಸೈಕಲ್ ಅಥವಾ ಮೋಟಾರ್ ಸೈಕಲ್ ಇರಬೇಕು",
    reqLicense: "ಲೈಸೆನ್ಸ್: ದ್ವಿಚಕ್ರ ವಾಹನ ಚಾಲನಾ ಪರವಾನಗಿ ಇರಬೇಕು",
    reqPhone: "ಸ್ಮಾರ್ಟ್ಫೋನ್: ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕವಿರುವ ಆಂಡ್ರಾಯ್ಡ್ ಮೊಬೈಲ್",
    reqArea: "ಸ್ಥಳೀಯ ಜ್ಞಾನ: ಸುತ್ತಮುತ್ತಲಿನ ಹಳ್ಳಿಗಳು ಮತ್ತು ದಾರಿಗಳ ಬಗ್ಗೆ ತಿಳುವಳಿಕೆ",
    benHours: "ಅನುಕೂಲಕರ ಸಮಯ: ನಿಮಗೆ ಇಷ್ಟವಾದ ಸಮಯದಲ್ಲಿ ಕೆಲಸ ಮಾಡಬಹುದು",
    benPayouts: "ವಾರದ ಪಾವತಿ: ಹಣ ನೇರವಾಗಿ ನಿಮ್ಮ ಬ್ಯಾಂಕ್ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ",
    benIncentives: "ಹೆಚ್ಚುವರಿ ಭತ್ಯೆ: ರಾತ್ರಿ ಅಥವಾ ಮಳೆಗಾಲದ ಡೆಲಿವರಿಗಳಿಗೆ ವಿಶೇಷ ಬೋನಸ್",
    benSupport: "ಅಪಘಾತ ವಿಮೆ ಸುರಕ್ಷತೆ ಮತ್ತು ವೈದ್ಯಕೀಯ ನೆರವು",
    registerFormTitle: "ನೋಂದಣಿ ಫಾರಂ (Form)",
    regName: "ಪೂರ್ಣ ಹೆಸರು",
    regPhone: "ಫೋನ್ ಸಂಖ್ಯೆ",
    regVehicleType: "ವಾಹನದ ಪ್ರಕಾರ",
    regVillage: "ಕೆಲಸ ಮಾಡಲು ಇಚ್ಛಿಸುವ ಗ್ರಾಮ / ಬ್ಲಾಕ್",
    regLicenseNo: "ಡ್ರೈವಿಂಗ್ ಲೈಸೆನ್ಸ್ ಸಂಖ್ಯೆ",
    regSubmit: "ಅರ್ಜಿ ಸಲ್ಲಿಸಿ",
    regSuccess: "ಧನ್ಯವಾದಗಳು! ನಮ್ಮ ಬ್ಲಾಕ್ ಸಂಯೋಜಕರು 24 ಗಂಟೆಗಳಲ್ಲಿ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ.",
    searchTitle: "ಫೋಟೋ ಮೂಲಕ ಔಷಧಿ ಹುಡುಕಿ",
    searchSubtitle: "ಔಷಧಿ ಪ್ಯಾಕೆಟ್ ಅಥವಾ ವೈದ್ಯರ ಚೀಟಿ ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ, ನಮ್ಮ ಕಂಪ್ಯೂಟರ್ ಅದನ್ನು ಗುರುತಿಸುತ್ತದೆ.",
    capturePhoto: "ಕ್ಯಾಮೆರಾದಿಂದ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    uploadPhoto: "ಫೋಟೋ ಅಪ್ಲೋಡ್ ಮಾಡಿ",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    retakePhoto: "ಮತ್ತೆ ಫೋಟೋ ತೆಗೆಯಿರಿ",
    selectFromGallery: "ಗ್ಯಾಲರಿಯಿಂದ ಆರಿಸಿ",
    validationSize: "ಫೈಲ್ ಗಾತ್ರ 5MB ಗಿಂತ ಕಡಿಮೆ ಇರಬೇಕು.",
    validationType: "JPG, JPEG ಮತ್ತು PNG ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ಬಳಸಬಹುದು.",
    scanning: "ಚಿತ್ರವನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ... ಔಷಧಿಯ ಹೆಸರನ್ನು ಗುರುತಿಸಲಾಗುತ್ತಿದೆ...",
    matchingMeds: "ನಮ್ಮ ಬಳಿ ಲಭ್ಯವಿರುವ ಔಷಧಿಗಳು:",
    noMatch: "ಯಾವುದೇ ಔಷಧಿ ಪಂದ್ಯವಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಸಹಾಯವಾಣಿ ಅಥವಾ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
    translateTitle: "ಭಾಷಾ ಅನುವಾದ ಬೇಕೇ?",
    translateBody: "ಇಂಗ್ಲಿಷಿನಲ್ಲಿರುವ ವೈದ್ಯರ ಚೀಟಿಯನ್ನು ನಿಮ್ಮ ಮೊಬೈಲ್ ನ 'Google Translate' ಆಪ್ ಬಳಸಿ ಕ್ಯಾಮೆರಾ ತೋರಿಸುವ ಮೂಲಕ ನಿಮ್ಮ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ತಕ್ಷಣವೇ ನೋಡಬಹುದು.",
    translateStep1: "1. ಪ್ಲೇ ಸ್ಟೋರ್ ನಿಂದ Google Translate ಆಪ್ ಡೌನ್ ಲೋಡ್ ಮಾಡಿ.",
    translateStep2: "2. ಆಪ್ ತೆರೆದು English ನಿಂದ Kannada ಗೆ ಆಯ್ಕೆ ಮಾಡಿ.",
    translateStep3: "3. 'Camera' ಗುರುತು ಒತ್ತಿ ನಿಮ್ಮ ವೈದ್ಯರ ಚೀಟಿ ಪೇಪರ್ ಮೇಲೆ ತೋರಿಸಿ.",
    familyTitle: "ನನ್ನ ಕುಟುಂಬದ ಖಾತೆ / Family Account",
    familySubtitle: "ಒಂದೇ ಖಾತೆಯ ಅಡಿಯಲ್ಲಿ ನಿಮ್ಮ ಮಕ್ಕಳು, ಪತ್ನಿ/ಪತಿ ಮತ್ತು ಪೋಷಕರ ಆರೋಗ್ಯ ವಿವರಗಳನ್ನು ನಿರ್ವಹಿಸಿ.",
    addMember: "ಕುಟುಂಬದ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ",
    relationship: "ಸಂಬಂಧ / Relationship",
    ageYears: "ವಯಸ್ಸು (ವರ್ಷಗಳಲ್ಲಿ)",
    gender: "ಲಿಂಗ / Gender",
    medicalHistory: "ಹಿಂದಿನ ಕಾಯಿಲೆಗಳ ವಿವರ (ಅಲರ್ಜಿ, ಅಸ್ತಮಾ, ಮಧುಮೇಹ ಇತ್ಯಾದಿ)",
    relationSelf: "ಸ್ವಂತ",
    relationSpouse: "ಪತ್ನಿ / ಪತಿ",
    relationChild: "ಮಗು",
    relationParent: "ತಾಯಿ / ತಂದೆ",
    relationSibling: "ಸಹೋದರ / ಸಹೋದರಿ",
    relationOther: "ಇತರ",
    noFamily: "ಇನ್ನೂ ಯಾವುದೇ ಕುಟುಂಬ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿಲ್ಲ.",
    removeMember: "ಸದಸ್ಯರನ್ನು ತೆಗೆದುಹಾಕಿ"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('rc_lang');
    return (saved as Language) || 'en';
  });

  const [isBilingual, setIsBilingual] = useState<boolean>(() => {
    const saved = localStorage.getItem('rc_bilingual');
    return saved ? saved === 'true' : true; // Default to true for rural support!
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('rc_lang', lang);
  };

  const toggleBilingual = () => {
    setIsBilingual(prev => {
      const val = !prev;
      localStorage.setItem('rc_bilingual', String(val));
      return val;
    });
  };

  // Translation helper
  const t = (key: string): string => {
    const localText = translations[language]?.[key] || translations['en']?.[key] || key;
    const englishText = translations['en']?.[key] || key;

    if (isBilingual && language !== 'en' && localText !== englishText) {
      // Return combined label e.g., "दवाइयाँ / Medicines" or "मुख्य पृष्ठ / Home"
      return `${localText} / ${englishText}`;
    }

    return localText;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isBilingual, toggleBilingual }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};
